### PR TITLE
Pull issues from branch names. Addresses #5.

### PR DESCRIPTION
**Pull request by nickmbailey**
### Checklist

- [x] All new jobs, commands, executors, parameters have descriptions
- [x] Examples have been added for any significant new features
- [x] README has been updated, if necessary

### Motivation, issues

This allows jira issue links to be pulled from the branch name instead of the commit message.

https://github.com/CircleCI-Public/jira-connect-orb/issues/5

### Description

Apply the same regex used for commit message to the branch name.

### CODE REVIEW

**Comment by iynere** [comment]
thank you ! @nickmbailey

**Comment by nickmbailey** [comment]
Thanks for the quick merge! When can I expect to see this released?

**Comment by iynere** [comment]
it's already been released @nickmbailey orb-publishing is automated for commits on master:

https://github.com/CircleCI-Public/jira-connect-orb/issues/5

**Comment by nickmbailey** [comment]
Thanks!

**Comment by lubieniebieski** [comment]
Thanks @nickmbailey! 👌

**Pull request merged**
