### PR TITLE
:bug: Use the login field instead the name to avoid profile without name [semver:patch]

### PR DESCRIPTION
**Pull request by mauriciojovel**
### Checklist
- [ X] All new jobs, commands, executors, parameters have descriptions
- [ X] Examples have been added for any significant new features
- [ X] README has been updated, if necessary

### Motivation, issues

This commit fix the problem describe in this bug https://github.com/CircleCI-Public/jira-connect-orb/issues/40.

### Description

Change the lookup field `name` for `login`

### CODE REVIEW

**Comment by KyleTryon** [comment]
Hello @mauriciojovel,

While we took a different approach, would you mind letting us know if this issue is now resolved in 1.1.6?

**Comment by mauriciojovel** [comment]
Hi,

The problems is happening in the version 1.1.6

Screenshot 2020-04-08 09 32 39

**Comment by KyleTryon** [comment]
@mauriciojovel hey I realize now the last patch I added was unnecessary and actually accomplishes pretty much the same thing as before. I will likely revert this shortly.

Can you confirm for me, are you using a user token or a project token?

Could you manually attempt to curl this endpoint with your token and ensure you are getting back an authenticated response?

**Comment by mauriciojovel** [comment]
Hi @KyleTryon ,

I'm using user token, when I tried to use the project token the process fails with the error `You must login first`

**Pull request merged**
