### PR TITLE
[semver:patch] Issue #35 - Tagged Builds no longer fail

### LINKED ISSUE #35: jq: error (at <stdin>:549): null (null) cannot be matched, as it is not a string
### Orb version

1.1.2

### What happened

When building a git tag in Circle, there is no branch. In the /tmp/job_info.json, the branch key is null.
- `"branch": null,` 

### Expected behavior

orb should fail gracefully upon not finding any ISSUE_KEYS

### PR DESCRIPTION
**Pull request by randywallace**
### Checklist

- [x] All new jobs, commands, executors, parameters have descriptions
- [x] Examples have been added for any significant new features
- [x] README has been updated, if necessary

### Motivation, issues

Resolves #35 

### Description

Implement suggested jq query.  Tested in a personal dev orb against our Org, and it no longer fails.

### CODE REVIEW

**Comment by znotdead** [comment]
Any progress? Thanks!

**Comment by randywallace** [comment]
I've since committed to using a fork build of this orb for our org.  That being said, any feedback from reviewers will be adjudicated; as it stands, I'm not sure what I can do here to push this forward.

**Comment by midleman** [comment]
Hello, I also ran into this issue. Is there any update on this?

**Comment by gmemstr** [comment]
Appreciate the pull request! Apologies it took a while to get reviewed, we're working on streamlining our process of maitaining orbs :)

**Pull request merged**
